FROM node:14

RUN npm install -g -f yarn

RUN yarn global add pm2 knex

# Create App Directory
WORKDIR /home/lafia-service

COPY package*.json ./

RUN yarn

COPY . .

# Set env variables for captainRover
ARG PORT=${PORT}
ARG NODE_ENV=${NODE_ENV}
ARG POSTGRES_PORT=${POSTGRES_PORT}
ARG POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ARG POSTGRES_HOST=${POSTGRES_HOST}
ARG POSTGRES_DBNAME=${POSTGRES_DBNAME}
ARG POSTGRES_USER=${POSTGRES_USER}
ARG JWT_SECRETE_KEY=${JWT_SECRETE_KEY}
ARG CLOUDINARY_URL=${CLOUDINARY_URL}
ARG PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY}
ARG PAYSTACK_API=${PAYSTACK_API}
ARG TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
ARG TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
ARG TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
ARG TWILIO_MESSAGING_SERVICE_SID=${TWILIO_MESSAGING_SERVICE_SID}
ARG EMAIL_ADDRESS=${EMAIL_ADDRESS}
ARG EMAIL_PASSWORD=${EMAIL_PASSWORD}
ARG CAPROVER_GIT_COMMIT_SHA=${CAPROVER_GIT_COMMIT_SHA}
ENV CAPROVER_GIT_COMMIT_SHA=${CAPROVER_GIT_COMMIT_SHA}

RUN yarn tsc && yarn mg:latest && yarn seed:run

EXPOSE 8045

CMD ["node", "dist/src/app/index.js"]
