const TYPES = {
  // controllers
  OtpController: Symbol('OtpController'),
  RoleController: Symbol('RoleController'),
  UserController: Symbol('UserController'),
  CardController: Symbol('CardController'),
  StatusController: Symbol('StatusController'),
  ParcelController: Symbol('ParcelController'),
  WalletController: Symbol('WalletController'),
  PaymentController: Symbol('PaymentController'),
  DiscountController: Symbol('DiscountController'),
  DropPointController: Symbol('DropPointController'),
  TravellerController: Symbol('TravellerController'),
  PermissionController: Symbol('PermissionController'),
  BankDetailController: Symbol('BankDetailController'),
  TransactionController: Symbol('TransactionController'),
  PaymentSettingController: Symbol('PaymentSettingController'),
  NotificationSettingController: Symbol('NotificationSettingController'),

  // service
  UserService: Symbol('UserService'),
  RoleService: Symbol('RoleService'),
  CardService: Symbol('CardService'),
  StatusService: Symbol('StatusService'),
  ParcelService: Symbol('ParcelService'),
  WalletService: Symbol('WalletService'),
  MessageService: Symbol('MessageService'),
  ReceiverService: Symbol('ReceiverService'),
  DiscountService: Symbol('DiscountService'),
  PaystackService: Symbol('PaystackService'),
  DropPointService: Symbol('DropPointService'),
  GuarantorService: Symbol('GuarantorService'),
  TravellerService: Symbol('TravellerService'),
  PermissionService: Symbol('PermissionService'),
  CloudinaryService: Symbol('CloudinaryService'),
  BankDetailService: Symbol('BankDetailService'),
  TransactionService: Symbol('TransactionService'),
  ParcelStatusService: Symbol('ParcelStatusService'),
  NotificationService: Symbol('NotificationService'),
  VerificationService: Symbol('VerificationService'),
  UserDiscountService: Symbol('UserDiscountService'),
  PaymentSettingService: Symbol('PaymentSettingService'),
  SendersReceiversService: Symbol('SendersReceiversService'),
  RolesPermissionsService: Symbol('RolesPermissionsService'),
  TransactionStatusService: Symbol('TransactionStatusService'),
  NotificationSettingService: Symbol('NotificationSettingService'),
  TwilioServiceService: Symbol('TwilioServiceService'),

  // repositories
  UserRepository: Symbol('UserRepository'),
  RoleRepository: Symbol('RoleRepository'),
  CardRepository: Symbol('CardRepository'),
  ParcelRepository: Symbol('ParcelRepository'),
  StatusRepository: Symbol('StatusRepository'),
  WalletRepository: Symbol('WalletRepository'),
  DiscountRepository: Symbol('DiscountRepository'),
  ReceiverRepository: Symbol('ReceiverRepository'),
  GuarantorRepository: Symbol('GuarantorRepository'),
  TravellerRepository: Symbol('TravellerRepository'),
  DropPointRepository: Symbol('DropPointRepository'),
  BankDetailRepository: Symbol('BankDetailRepository'),
  PermissionRepository: Symbol('PermissionRepository'),
  TransactionRepository: Symbol('TransactionRepository'),
  ParcelStatusRepository: Symbol('ParcelStatusRepository'),
  NotificationRepository: Symbol('NotificationRepository'),
  UserDiscountRepository: Symbol('UserDiscountRepository'),
  VerificationRepository: Symbol('VerificationRepository'),
  TwilioServiceRepository: Symbol('TwilioServiceRepository'),
  PaymentSettingRepository: Symbol('PaymentSettingRepository'),
  RolesPermissionsRepository: Symbol('RolesPermissionsRepository'),
  SendersReceiversRepository: Symbol('SendersReceiversRepository'),
  TransactionStatusRepository: Symbol('TransactionStatusRepository'),
  NotificationSettingRepository: Symbol('NotificationSettingRepository'),
};


export default TYPES;
